/**
 * Internal Tickets API
 * GET /api/messages/tickets - List internal tickets
 * POST /api/messages/tickets - Create internal ticket
 */

import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth/config';
import {
  getInternalTickets,
  createInternalTicket,
} from '@/lib/db/conversations';
import type {
  ConversationStatus,
  Platform,
  AssignedTeam,
  Priority,
} from '@/lib/db/conversations';

/**
 * GET /api/messages/tickets
 * List all internal tickets with optional filtering and pagination
 *
 * Query parameters:
 * - status: Filter by status (open, in_progress, resolved, closed)
 * - platform: Filter by platform (ozean_licht, kids_ascension)
 * - assignedTeam: Filter by team (support, dev, tech, admin, spiritual)
 * - assignedAgentId: Filter by assigned agent UUID
 * - requesterId: Filter by requester UUID
 * - search: Search by title or ticket number
 * - limit: Results per page (default: 50, max: 100)
 * - offset: Pagination offset (default: 0)
 * - orderBy: Sort column (default: updated_at)
 * - orderDirection: Sort direction (asc, desc, default: desc)
 */
export async function GET(request: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // Parse query parameters
    const searchParams = request.nextUrl.searchParams;
    const status = searchParams.get('status') as ConversationStatus | null;
    const platform = searchParams.get('platform') as Platform | null;
    const assignedTeam = searchParams.get('assignedTeam') as AssignedTeam | null;
    const assignedAgentId = searchParams.get('assignedAgentId');
    const search = searchParams.get('search');
    const limit = parseInt(searchParams.get('limit') || '50', 10);
    const offset = parseInt(searchParams.get('offset') || '0', 10);
    const orderBy = searchParams.get('orderBy') || 'updated_at';
    const orderDirection = (searchParams.get('orderDirection') || 'desc') as 'asc' | 'desc';

    // Validate enum values
    const validStatuses: ConversationStatus[] = ['open', 'in_progress', 'resolved', 'closed'];
    const validPlatforms: Platform[] = ['ozean_licht', 'kids_ascension'];
    const validTeams: AssignedTeam[] = ['support', 'dev', 'tech', 'admin', 'spiritual'];

    if (status && !validStatuses.includes(status)) {
      return NextResponse.json(
        { error: `Invalid status. Must be one of: ${validStatuses.join(', ')}` },
        { status: 400 }
      );
    }

    if (platform && !validPlatforms.includes(platform)) {
      return NextResponse.json(
        { error: `Invalid platform. Must be one of: ${validPlatforms.join(', ')}` },
        { status: 400 }
      );
    }

    if (assignedTeam && !validTeams.includes(assignedTeam)) {
      return NextResponse.json(
        { error: `Invalid team. Must be one of: ${validTeams.join(', ')}` },
        { status: 400 }
      );
    }

    // Validate search query length
    if (search && search.length > 200) {
      return NextResponse.json(
        { error: 'Search query is too long (max 200 characters)' },
        { status: 400 }
      );
    }

    // Validate pagination parameters
    if (isNaN(limit) || limit < 1) {
      return NextResponse.json(
        { error: 'Limit must be a positive number' },
        { status: 400 }
      );
    }

    if (isNaN(offset) || offset < 0) {
      return NextResponse.json(
        { error: 'Offset must be zero or a positive number' },
        { status: 400 }
      );
    }

    // Fetch internal tickets
    const result = await getInternalTickets({
      status: status || undefined,
      platform: platform || undefined,
      assignedTeam: assignedTeam || undefined,
      assignedAgentId: assignedAgentId || undefined,
      search: search || undefined,
      limit,
      offset,
      orderBy,
      orderDirection,
    });

    return NextResponse.json({
      tickets: result.conversations,
      total: result.total,
      limit,
      offset,
    });
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('[API] Failed to fetch internal tickets:', error);
    return NextResponse.json(
      { error: 'Failed to fetch internal tickets' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/messages/tickets
 * Create a new internal ticket
 *
 * Body parameters:
 * - title: Ticket title (required)
 * - description: Ticket description - optional
 * - assignedTeam: Assigned team (support, dev, tech, admin, spiritual) - required
 * - priority: Priority level (low, normal, high, urgent) - optional, defaults to normal
 * - requesterId: Requester user ID (required)
 * - linkedConversationId: Linked conversation ID - optional
 * - metadata: Additional metadata - optional
 *
 * Note: ticket_number is auto-generated by database trigger based on assigned_team
 */
export async function POST(request: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { title, description, assignedTeam, priority, requesterId, linkedConversationId, metadata } = body;

    // Validate required fields
    if (!title) {
      return NextResponse.json(
        { error: 'Title is required' },
        { status: 400 }
      );
    }

    if (!assignedTeam) {
      return NextResponse.json(
        { error: 'Assigned team is required' },
        { status: 400 }
      );
    }

    if (!requesterId) {
      return NextResponse.json(
        { error: 'Requester ID is required' },
        { status: 400 }
      );
    }

    // Validate title length
    if (title.length > 200) {
      return NextResponse.json(
        { error: 'Title is too long (max 200 characters)' },
        { status: 400 }
      );
    }

    // Validate description length if provided
    if (description && description.length > 2000) {
      return NextResponse.json(
        { error: 'Description is too long (max 2000 characters)' },
        { status: 400 }
      );
    }

    // Validate assignedTeam
    const validTeams: AssignedTeam[] = ['support', 'dev', 'tech', 'admin', 'spiritual'];
    if (!validTeams.includes(assignedTeam)) {
      return NextResponse.json(
        { error: `Invalid team. Must be one of: ${validTeams.join(', ')}` },
        { status: 400 }
      );
    }

    // Validate priority if provided
    if (priority) {
      const validPriorities: Priority[] = ['low', 'normal', 'high', 'urgent'];
      if (!validPriorities.includes(priority)) {
        return NextResponse.json(
          { error: `Invalid priority. Must be one of: ${validPriorities.join(', ')}` },
          { status: 400 }
        );
      }
    }

    // Create the ticket
    const conversation = await createInternalTicket(
      {
        title,
        description,
        assignedTeam,
        priority: priority || 'normal',
        requesterId,
        linkedConversationId,
        metadata,
      },
      session.user.id
    );

    return NextResponse.json({ conversation, ticket: conversation }, { status: 201 });
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('[API] Failed to create internal ticket:', error);
    return NextResponse.json(
      { error: 'Failed to create internal ticket' },
      { status: 500 }
    );
  }
}
