import { Course } from '@/types/course';

// MinIO S3 base URL for course images
const MINIO_BASE_URL = process.env.MINIO_PUBLIC_URL || '/images/courses';

export const mockCourses: Course[] = [
  {
    id: '1',
    slug: 'lcq-basis',
    title: 'LCQ® Basis Kurs',
    subtitle: 'Grundlagen der Light Code Quantum Transformation',
    description: 'Entdecke die Grundlagen der LCQ® Methode und beginne deine Reise zur spirituellen Transformation. Dieser Kurs vermittelt dir die essenziellen Werkzeuge für deine persönliche Entwicklung.',
    price: 497,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/lcq-basis.jpg`,
    course_code: 101,
    tags: ['LCQ', 'Basis'],
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'lcq-advanced',
    title: 'LCQ® Advanced',
    subtitle: 'Vertiefe deine LCQ® Praxis',
    description: 'Erweitere dein Wissen über Light Code Quantum und lerne fortgeschrittene Techniken für tiefgreifende Transformation und spirituelles Wachstum.',
    price: 797,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/lcq-advanced.jpg`,
    course_code: 201,
    tags: ['LCQ', 'Advanced'],
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-01-05T00:00:00Z',
  },
  {
    id: '3',
    slug: 'lcq-master',
    title: 'LCQ® Master Programm',
    subtitle: 'Werde zum LCQ® Master',
    description: 'Das umfassende Master-Programm für angehende LCQ® Praktizierende. Lerne, andere auf ihrer spirituellen Reise zu begleiten und transformative Sitzungen zu geben.',
    price: 997,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/lcq-master.jpg`,
    course_code: 301,
    tags: ['LCQ', 'Master'],
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: '4',
    slug: 'meditation-basics',
    title: 'Meditation für Einsteiger',
    subtitle: 'Finde inneren Frieden durch Meditation',
    description: 'Ein sanfter Einstieg in die Welt der Meditation. Lerne verschiedene Techniken kennen und finde deinen Weg zur inneren Ruhe und Klarheit.',
    price: 297,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/meditation-basics.jpg`,
    course_code: 110,
    tags: ['Meditation', 'Basis'],
    created_at: '2025-01-12T00:00:00Z',
    updated_at: '2025-01-12T00:00:00Z',
  },
  {
    id: '5',
    slug: 'chakra-healing',
    title: 'Chakra Heilung & Energiearbeit',
    subtitle: 'Harmonisiere deine Energiezentren',
    description: 'Lerne die sieben Hauptchakren kennen und erfahre, wie du durch gezielte Übungen Blockaden löst und deine Energie ins Gleichgewicht bringst.',
    price: 447,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/chakra-healing.jpg`,
    course_code: 120,
    tags: ['Energie', 'Heilung'],
    created_at: '2025-01-15T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: '6',
    slug: 'astral-projection',
    title: 'Astralreisen Intensivkurs',
    subtitle: 'Erkunde außerkörperliche Dimensionen',
    description: 'Entdecke die faszinierende Welt der Astralreisen. Lerne sichere Techniken, um bewusst außerkörperliche Erfahrungen zu machen und neue Dimensionen zu erforschen.',
    price: 697,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/astral-projection.jpg`,
    course_code: 210,
    tags: ['Astral', 'Advanced'],
    created_at: '2025-01-18T00:00:00Z',
    updated_at: '2025-01-18T00:00:00Z',
  },
  {
    id: '7',
    slug: 'crystal-healing',
    title: 'Kristallheilung Masterclass',
    subtitle: 'Die Kraft der Kristalle nutzen',
    description: 'Tauche ein in die magische Welt der Kristalle. Lerne, wie du Heilsteine für Energiearbeit, Meditation und persönliche Transformation einsetzen kannst.',
    price: 397,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/crystal-healing.jpg`,
    course_code: 130,
    tags: ['Kristalle', 'Heilung'],
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-01-20T00:00:00Z',
  },
  {
    id: '8',
    slug: 'sacred-geometry',
    title: 'Heilige Geometrie & Manifestation',
    subtitle: 'Universelle Muster für Transformation',
    description: 'Entdecke die universellen Muster der heiligen Geometrie und lerne, wie du sie für Manifestation, Heilung und spirituelles Wachstum nutzen kannst.',
    price: 547,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/sacred-geometry.jpg`,
    course_code: 140,
    tags: ['Geometrie', 'Manifestation'],
    created_at: '2025-01-22T00:00:00Z',
    updated_at: '2025-01-22T00:00:00Z',
  },
  {
    id: '9',
    slug: 'shamanic-journey',
    title: 'Schamanische Reisen',
    subtitle: 'Alte Weisheit für moderne Zeiten',
    description: 'Verbinde dich mit uralten schamanischen Praktiken. Lerne Trommelreisen, Krafttierarbeit und spirituelle Heilungstechniken aus indigenen Traditionen.',
    price: 647,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/shamanic-journey.jpg`,
    course_code: 220,
    tags: ['Schamanismus', 'Reise'],
    created_at: '2025-01-25T00:00:00Z',
    updated_at: '2025-01-25T00:00:00Z',
  },
  {
    id: '10',
    slug: 'akashic-records',
    title: 'Akasha Chronik Lesung',
    subtitle: 'Zugang zur universellen Bibliothek',
    description: 'Lerne, die Akasha Chronik zu öffnen und Informationen über vergangene Leben, karmische Muster und deine Seelenaufgabe zu empfangen.',
    price: 747,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/akashic-records.jpg`,
    course_code: 230,
    tags: ['Akasha', 'Advanced'],
    created_at: '2025-01-28T00:00:00Z',
    updated_at: '2025-01-28T00:00:00Z',
  },
  {
    id: '11',
    slug: 'breathwork-mastery',
    title: 'Breathwork Mastery',
    subtitle: 'Transformative Atemarbeit',
    description: 'Entdecke die transformative Kraft des bewussten Atmens. Lerne verschiedene Breathwork-Techniken für Heilung, Energiearbeit und Bewusstseinserweiterung.',
    price: 497,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/breathwork.jpg`,
    course_code: 150,
    tags: ['Breathwork', 'Heilung'],
    created_at: '2025-02-01T00:00:00Z',
    updated_at: '2025-02-01T00:00:00Z',
  },
  {
    id: '12',
    slug: 'sound-healing',
    title: 'Klangheiling & Frequenzmedizin',
    subtitle: 'Heilende Schwingungen',
    description: 'Erfahre die heilende Wirkung von Klängen und Frequenzen. Lerne mit Klangschalen, Gongs und Stimmgabeln zu arbeiten und heilende Klangreisen zu gestalten.',
    price: 597,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/sound-healing.jpg`,
    course_code: 160,
    tags: ['Klang', 'Heilung'],
    created_at: '2025-02-05T00:00:00Z',
    updated_at: '2025-02-05T00:00:00Z',
  },
  {
    id: '13',
    slug: 'intuition-development',
    title: 'Intuitionsentwicklung',
    subtitle: 'Stärke deine innere Stimme',
    description: 'Aktiviere und stärke deine intuitive Wahrnehmung. Lerne, deiner inneren Führung zu vertrauen und klare intuitive Botschaften zu empfangen.',
    price: 447,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/intuition.jpg`,
    course_code: 170,
    tags: ['Intuition', 'Entwicklung'],
    created_at: '2025-02-08T00:00:00Z',
    updated_at: '2025-02-08T00:00:00Z',
  },
  {
    id: '14',
    slug: 'past-life-regression',
    title: 'Rückführungen & Karma-Heilung',
    subtitle: 'Löse alte karmische Muster',
    description: 'Reise in vergangene Leben und heile karmische Blockaden. Lerne sichere Rückführungstechniken und erhalte tiefe Einblicke in deine Seeleneise.',
    price: 697,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/past-life.jpg`,
    course_code: 240,
    tags: ['Karma', 'Rückführung'],
    created_at: '2025-02-10T00:00:00Z',
    updated_at: '2025-02-10T00:00:00Z',
  },
  {
    id: '15',
    slug: 'moon-magic',
    title: 'Mondmagie & Rituale',
    subtitle: 'Arbeite mit den Mondzyklen',
    description: 'Verbinde dich mit den zyklischen Energien des Mondes. Lerne kraftvolle Rituale für Neumond, Vollmond und die verschiedenen Mondphasen.',
    price: 397,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/moon-magic.jpg`,
    course_code: 180,
    tags: ['Mond', 'Rituale'],
    created_at: '2025-02-12T00:00:00Z',
    updated_at: '2025-02-12T00:00:00Z',
  },
  {
    id: '16',
    slug: 'energy-protection',
    title: 'Energetischer Schutz',
    subtitle: 'Schütze deine Energie',
    description: 'Lerne effektive Techniken zum Schutz deiner Energie. Erfahre, wie du dich vor energetischen Angriffen schützt und deine Aura stärkst.',
    price: 347,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/protection.jpg`,
    course_code: 190,
    tags: ['Schutz', 'Energie'],
    created_at: '2025-02-15T00:00:00Z',
    updated_at: '2025-02-15T00:00:00Z',
  },
  {
    id: '17',
    slug: 'divine-feminine',
    title: 'Das göttliche Weibliche',
    subtitle: 'Erwecke deine weibliche Kraft',
    description: 'Verbinde dich mit der göttlichen weiblichen Energie in dir. Heile Wunden, aktiviere deine Schöpferkraft und finde zurück zu deiner authentischen Weiblichkeit.',
    price: 547,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/divine-feminine.jpg`,
    course_code: 250,
    tags: ['Weiblich', 'Heilung'],
    created_at: '2025-02-18T00:00:00Z',
    updated_at: '2025-02-18T00:00:00Z',
  },
  {
    id: '18',
    slug: 'quantum-healing',
    title: 'Quantum Healing Intensiv',
    subtitle: 'Heilung auf Quantenebene',
    description: 'Entdecke die Quantenphysik der Heilung. Lerne, wie du durch Bewusstseinsarbeit auf Quantenebene tiefgreifende Transformation bewirken kannst.',
    price: 897,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/quantum-healing.jpg`,
    course_code: 310,
    tags: ['Quantum', 'Heilung', 'Master'],
    created_at: '2025-02-20T00:00:00Z',
    updated_at: '2025-02-20T00:00:00Z',
  },
  {
    id: '19',
    slug: 'manifestation-mastery',
    title: 'Manifestation Mastery',
    subtitle: 'Erschaffe deine Realität',
    description: 'Werde zum bewussten Schöpfer deiner Realität. Lerne kraftvolle Manifestationstechniken und setze die universellen Gesetze für deine Wünsche ein.',
    price: 647,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/manifestation.jpg`,
    course_code: 260,
    tags: ['Manifestation', 'Schöpferkraft'],
    created_at: '2025-02-22T00:00:00Z',
    updated_at: '2025-02-22T00:00:00Z',
  },
  {
    id: '20',
    slug: 'spiritual-business',
    title: 'Spirituelles Business aufbauen',
    subtitle: 'Deine spirituelle Berufung leben',
    description: 'Lerne, wie du deine spirituelle Gabe zum Beruf machst. Von der Positionierung über Marketing bis zur Kundengewinnung - dein Weg in die Selbstständigkeit.',
    price: 997,
    is_public: true,
    thumbnail_url_desktop: `${MINIO_BASE_URL}/spiritual-business.jpg`,
    course_code: 320,
    tags: ['Business', 'Master'],
    created_at: '2025-02-25T00:00:00Z',
    updated_at: '2025-02-25T00:00:00Z',
  },
];

// Mock user for demo mode
export const mockUser = {
  id: 'demo-user-123',
  email: 'demo@ozean-licht.dev',
  created_at: '2024-01-01T00:00:00Z',
  user_metadata: {
    full_name: 'Demo User',
    avatar_url: 'https://api.dicebear.com/7.x/initials/svg?seed=Demo&backgroundColor=1a2a3a',
  },
};
