export { LoginForm } from './LoginForm'
export { RegisterForm } from './RegisterForm'
export { PasswordResetForm } from './PasswordResetForm'
export { MagicLinkForm } from './MagicLinkForm'
export { ContactForm } from './ContactForm'
